jaffle_shop:
    target: dev
    outputs:
        dev:
            type: redshift
            host: "{{ env_var('REDSHIFT_HOSTNAME') }}"
            user: "{{ env_var('REDSHIFT_USER') }}"
            password: "{{ env_var('REDSHIFT_PASSWORD') }}"
            port: 5439
            dbname: dev
            schema: sewi
            threads: 4
            keepalives_idle: 240 # default 240 seconds
            connect_timeout: 10 # default 10 seconds